### ISSUE TITLE
Policy on titles

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextmp-popit#129]
I think we should have some sort of consistent policy on titles (and post-nominals, but that hasn't come up yet).

- Should we include "Dr" before those people's names?
- Should we include "Sir" before those people's names?
- Should be suffix "MBE" on those people's names?

Edit: Another example, John Perry in Havant clearly wants to be styled with 'Cllr' as his title:

http://yournextmp.com/person/5136/cllr-john-perry

**Comment by mhl** [comment]
In the Popolo spec the Dr, Sir and Cllr would be `honorific_prefix` and MBE would be `honorific_suffix`:  http://www.popoloproject.com/specs/person/name-component.html

We could just add these to the edit form, but since that's about to be redesigned anyway, this would be worth including in https://github.com/mysociety/yournextmp-popit/issues/130

**Comment by edent** [comment]
Any update on this?  I notice that, eg https://yournextmp.com/person/4240, wishes to be styled "Dr".

Is it ok just to put that in the free text field?  How will it show up on the ballot?

**Comment by mhl** [comment]
There are now fields for pre-nominal and post-nominal honorifics, so I'm going to close this - I hope that's OK.

**Comment by tfgg** [comment]
Yep, I think this is sorted now!
