### ISSUE TITLE
Broken candidate images

### ISSUE THREAD

**Issue by edent** [mysociety/yournextmp-popit#135]
On http://yournextmp.com/person/4521/mark-mann

The image URL is `https://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4521%2Fimage%2F5481e93ab150e238702c0648/0/80`

The URL decoded image passed to the proxy is `https://yournextmp.popit.mysociety.org/persons/4521/image/5481e93ab150e238702c0648/0/80` which 404s.

The correct URL should be `https://yournextmp.popit.mysociety.org/persons/4521/image/5481e93ab150e238702c0648/`

That said, the image proxy doesn't seem to work.

Seems to happen on all candidate images that I've found.

**Comment by mhl** [comment]
Hi @edent  - sorry about this, the image proxy was working fine at the end of the last week, but it's now returning 504s for many images, as you've pointed out. Since it's the weekend, I've just backed out the change to using thumbnails via the proxy and redployed, so all the images should be working again. I've also created a bug for the problem with the image proxy, which we'll try to fix on Monday:

* https://github.com/mysociety/popit/issues/719

**Comment by mhl** [comment]
We believe that the underlying issue here is fixed now with https://github.com/mysociety/popit/pull/721 so I'm closing this issue, we can always reopen if it recurs.
