### ISSUE TITLE
Versioning data bug

### ISSUE THREAD

**Issue by lizconlan** [mysociety/yournextmp-popit#161]
Not sure it's a genuine problem, but... I updated the Twitter field in the PPC's data and have been attributed the changes (made by an admin?) of adding the image links.

https://yournextmp.com/person/5328

**Comment by lizconlan** [comment]
Can be a bit disconcerting when stuff's been removed:

https://yournextmp.com/person/1412

**Comment by andylolz** [comment]
This is even more prominent with the new candidate pages, since there are all sorts of new fields that appear (to do with the party logo, for instance.)

@mhl I wonder if this could be fixed (or masked) by only showing information about user-editable fields in the version data. So… Add a `{% if operation.path in visible_version_properties %}` [to the person-versions template](https://github.com/mysociety/yournextmp-popit/blob/master/candidates/templates/candidates/person-versions.html#L22-L32), and then add a `visible_version_properties` list to the context.

**Comment by mhl** [comment]
https://github.com/mysociety/yournextmp-popit/issues/181 is the same issue. I'd really like to take some time to think how to do this better in general - there are various other related bugs too.

**Comment by andylolz** [comment]
Absolutely. The issues with mobile view in #172 would also be improved by fixing this one.

**Comment by mhl** [comment]
This also comes up on any time when an edit is made outside the YourNextMP database; I'm not sure there's much that's worth doing about this at this stage, so I'm closing this - we can reopen it if https://github.com/mysociety/popit/issues/818 gets implemented.
