### ISSUE TITLE
Use party logo as candidate photo if no candidate photo

### ISSUE THREAD

**Issue by tfgg** [mysociety/yournextmp-popit#162]
Might makes things prettier (?) and satisfy some candidates who want to use the party logo instead of the photograph.

**Comment by mhl** [comment]
I'd really prefer that we showed the party logos in addition, even for people we have photos for.

As for "prettier", I'm not sure - the emblems the EC host are monochrome with white backgrounds, so it'd take some work to fit them into the site nicely.

**Comment by mhl** [comment]
I tried adding party logos in addition to candidate pictures in this pull request, but it looked so messy that I've abandoned that. I'd quite like to close this, since I don't like a the idea of some people having pictures and some party logos. (Especially now that we're using the party logos on the candidate pages, so they are at least prominent there.)

**Comment by mhl** [comment]
Closing this now
