### ISSUE TITLE
create-popit failing

### ISSUE THREAD

**Issue by glenpike** [mysociety/yournextmp-popit#169]
Trying to use the create-popit scripts to populate the data in a local installation, but https://github.com/mysociety/yournextmp-popit/blob/master/candidates/management/commands/candidates_create_popit.py#L133 points to a missing file (although I see it's ignored in git):

yournextmp-json_main-20140124-030234.json

Doesn't look like an export from YNMP live - is this file available, or internal?

**Comment by glenpike** [comment]
Probably doesn't matter - minor issue, hopefully worked around.

**Comment by mhl** [comment]
@glenpike Yeah, sorry about that - in early development the data dumps from the old YourNextMP (all the 2010 data) were hosted on the old yournextmp.com, but now that we've put the live site on that domain, they're not available any more. Perhaps we should commit them into the repository now, if @evdb would be OK with that?

However, on the broader question, currently I'd suggest using the `candidates_get_live_database` command instead, and importing it into your local popit with https://github.com/mysociety/yournextmp-popit#mirror-the-live-database-into-your-development-copy instead of `create-popit`.

**Comment by mhl** [comment]
I'll reopen this, if you don't mind, because there is stuff to do here, even if it's just "deprecate create-popit" :)

**Comment by glenpike** [comment]
Great, sorted with instructions, thanks :+1:

**Comment by mhl** [comment]
Using `candidates_get_live_database` is now documented in README.md, so I'm closing this.
