### ISSUE TITLE
license dilemma (or trilemma)

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextmp-popit#189]
We are currently offering YourNextMP data under CC-BY-SA. This has turned out to be problematic for at least one potential partner who can't cope with the ShareAlike part. We need to come to a resolution about what license we ideally want to offer the data under.

### Pros:

* Ideologically the best (from my point of view anyway)
* It gives us protection against other people taking the dataset, building on it, but then not contributing back to us any corrections or additions they make

### Cons:

* The ShareAlike is too restrictive for at least one media partner we want to work with

### What would be involved in re-licensing?

Nothing - it's already the license.

### Pros:

* Requires attribution, so word about the data-source will still spread through its use
* Would be fine with all the partners we've talked to so far

### Cons:

* Doesn't prevent commercial companies from incorporating the data into their dataset and selling it; they'd just have to make sure they give attribution.

### What would be involved in re-licensing?

This is tricky. We don't have a copyright assignment agreement that contributors were agreeing to, just this text on the "About" page:

> By submitting data to this site, you agree that it may be distributed from this site under CC-BY-SA or (in case we decide to offer it under alternative licenses after further discussion) CC0 or ODbL. 

... which annoyingly I didn't think to include CC-BY in. However, CC-BY is between CC-BY-SA / ODbL and CC0 in terms of permissiveness. I can't conceive of how someone who was happy with either of those ends of the spectrum might be unhappy with CC-BY. If we want to do this, I think the best option is probably:

* Send an email to all 500-ish contributors and say, "we're intending to change the licence under which the data can be used [+ explain that it won't make much / any difference to them] - if you object to this, please let us know - otherwise your contributions will be included in the relicensed data" If anyone *does* object, we could strip out their contributions.

## CC0

This is essentially disavowing copyright and putting the data into the public domain.

### Pros

* This would be the best for encouraging reuse, since there's no potential copyright encumberance at all.

### Cons

* Anyone could use the data and build on it without having to acknowledge YourNextMP at all

### What would be involved in re-licensing?

Since we said that contributors were agreeing that it might be relicensed as CC0, we wouldn't have to do anything except change the license on the About page. We would probably want to add a polite request that people mention that YourNextMP was the data source, even though it's not required.

## Discussion

There are some key unknowns here, including some questions @tfgg posed:

* [CC0 vs others] Would it be a significant problem if we didn't require attribution?
* [CC0 vs others] Is anyone we'd hope would use the data actually put off by the requirement to give attribution?
* [CC0 vs others] If we went for CC0, would commercial candidate list providers start incorporating our hard-won data? Do we mind about that?
* [CC-BY vs CC-BY-SA] If we went for CC-BY, would commercial candidate list providers start incorporating our data, and then give attribution? Do we mind about that?
* [CC-BY vs others] Would a carefully phrased email like that I suggested above be sufficient for CC-BY re-licensing? (I think OpenStreetMap did something like this in their Great Re-licensing.)

## Stray Observations

* For the future, this is all much simpler if you ask for copyright assignment (or for people to assert that their contributions are free of copyright restrictions) in the first place; this was actually suggested by @tfgg and @evdb early on, I should say.

* This kind of issue is terribly frustrating to deal with.

**Comment by mhl** [comment]
Someone's suggested to me another option: the wording on the About page probably allows us to make the data available under CC0 to a partner selectively, while still leaving the data as CC-BY-SA in general to anyone else. This might be the best compromise: if someone makes a really good case to us that they can't deal with CC-BY-SA and we think they'll be a partner we really want to use the data, then we could let them use it under CC0.

**Comment by paullenz** [comment]
+1 on that last comment

**Comment by paullenz** [comment]
As a more general point - does it matter hugely is people use the data without referencing YNMP?  Sure, it is lovely if they do, but surely impactful re-use of the data is the most important thing here?

**Comment by dracos** [comment]
@paullenz How will you be able to tell if it's impactful if you don't know they're using it?

**Comment by tfgg** [comment]
I agree that impact is the most important thing, and re-use is ultimately the main path to impact for ynmp. The only thing is whether attribution helps this by ensuring other people who might use the data discover us and whether it helps improve the data by driving corrections to us, also increasing impact by improving the data.

I also agree with Matthew that attribution/knowledge of use helps measure impact. If a commercial org sells our data without us knowing, we won't be able to say next time how important what we did was. I think these have to be balanced against considerations that nmght prevent re-users who will make up the bulk of our final impact.

**Comment by evdb** [comment]
Most of the data could be considered "facts" and as such not individually copyrightable. For example telephone numbers etc.

The stuff that the copyright most likely will apply to are the images. If the dataset were considered to be in two parts then the factual bit (phone numbers, addresses etc) could be have its license changed as there is no real original copyright to break (IANAL, AFAIK, etc, etc). The images then are harder to deal with. Depending on what the partner wants to do with the data that might short term be a quick way to release part of it to them with no SA restrictions.

**Comment by dracos** [comment]
@evdb There is a sui generis database right in the EU (acts like copyright for databases). This is covered by CC-BY-SA 4 and the ODbL.

**Comment by jarofgreen** [comment]
Interesting. I can see why you want attrib because i can see why you want to measure impact. 

I've been doing http://opentechcalendar.co.uk/ for years now and that's one of the issues I have; I've just been completely open and tried to deal with issues of measuring users later. Most of the time it's fine because I can point to areas that have demonstrable impact, but occasionally I have problems when someone (usually a potential sponsor) asks for concrete user figures.

I also have some specialist problems; I know more than 1 person imports OTC data straight into personal Google Calendar cos they told me which is great but thanks to how G.C. fetches data I can't tell how many.

Some general problems: I have big problems measuring conversions. Telling the difference between someone who browses site and thinks it's shit and someone who browses site, writes down details of event on bit of paper and has awesum evening is impossible from web stats.

I've never generally had a good solution to these problems that did not in some way involve knobbling the open data aspect in some way, which I want to avoid.

One thought is; is attribution really the best way to measure impact, or is it a surrogate? I guess it will help in the case of another group using data wholesale, but will it help in the case of measuring individual impact beyond that? What does measuring individual impact even mean for you?

For example, I spoke to a local company employee by chance recently, turned out they have  secretaries copying events from OTC to internal staff Google Calendar by hand! Impact = great! But attribution would have done nothing to measure that. (Also, I added a feature to make secretaries life easier :-) )

I don't know answer BTW; just some hopefully interesting thoughts .... attribution will hold some ppl back from re-use, so it should only be requrired if you think there are really good benefits.

**Comment by mhl** [comment]
@evdb Sorry, I wasn't clear in the ticket - I'm only thinking about the license of the database not including images, because their licensing is even more problematic. (I've added a note about the exception for the images to the [About page](https://yournextmp.com/help/about).)

**Comment by edent** [comment]
If the license is too permissive for one media partner, what's wrong with either educating them on *why* you want SA - or simply telling them to buy the data elsewhere?

The point of the "viral" nature of these sort of licenses is to *encourage* the spirit of sharing.

**Comment by mhl** [comment]
This has now been resolved to (I think) everyone's satisfaction; the data is still available under CC-BY-SA, but we've now introduced copyright assignment for contributions from the 4th of March onwards (making a one-off release into the public domain on that day) so that in special cases where it seems appropriate to license the data to particular partners are CC-BY, we can do that too. (There was rather more to it than that, but we believe that what we've done is sound and all the details aren't probably of general interest.)

@edent Personally, I absolutely agree :/
