### ISSUE TITLE
Staging is indexed by search engines

### ISSUE THREAD

**Issue by edent** [mysociety/yournextmp-popit#194]
Doing a search for some of the more unique candidates - eg https://www.google.co.uk/search?q=Matt+Officer+class+war - the first result is from http://candidates.staging.mysociety.org

I'd suggest shoving a `robots.txt` file on there and - given that the site is in full debug mode - password protecting it.

**Comment by mhl** [comment]
Oops, yes, I thought I'd added robots.txt already, but that was only for the PopIt backend. I've done that now: http://candidates.staging.mysociety.org/robots.txt ...

I'll password protect it once it seems to have been dropped from search indexes, and try to encourage that with Google Webmaster Tools.

To be honest, I think the risk from having the staging site publicly accessible with `DEBUG = True` is pretty low, since paths that you might discover through stack traces easy to infer anyway, since so much of our deployment infrastructure is public. But better safe than sorry, I suppose.

**Comment by mhl** [comment]
I added a robots.txt to disallow all pages on candidates.staging.mysociety.org some time ago, but there are still pages from there being returned - I've now used the Google Webmaster Tools to make a request to remove every page on the site from Google's search index; this is still pending.

**Comment by mhl** [comment]
OK, this seems to be fixed now.
