### ISSUE TITLE
Don't list deregistered parties on candidate list

### ISSUE THREAD

**Issue by symroe** [mysociety/yournextmp-popit#215]
https://twitter.com/paulbirch99/status/568718771122262016

Reported that the "Cannabis Law Reform party is defunct".  It's listed as "Statutorily Deregistered" on http://openelectoralcommission.org.uk/parties/PP1759/cannabis-law-reform/, so filtering out those parties from the list should be easy enough to do.

**Comment by mhl** [comment]
Just to add some more notes on this, since it's in the current sprint:

The selection of parties offered on the site is loaded from https://github.com/mysociety/yournextmp-popit/blob/master/data/all-parties-from-popit.json which is generated from https://github.com/mysociety/yournextmp-popit/blob/master/candidates/management/commands/candidates_dump_popit_parties_to_json.py so it should just be a case of updating the latter.

The other issue is that some 2015 candidates may be assigned to parties that are now dissolved - I think that should be dealt with as part of https://github.com/mysociety/yournextmp-popit/issues/260 though.

**Comment by mhl** [comment]
This should be fixed now, including reassigning anyone to a now-deregistered party.

**Comment by jf1** [comment]
Not sure if this is the same issue or slightly different, but de-registered parties appear in the drop-down list when editing a candidate's details. Example is: Get London Moving Party [De-registered 15/10/01]

I can understand keeping de-registered parties in the database but think users would benefit from these parties not appearing in lists relating to current elections.

**Comment by mhl** [comment]
@jf1 There's a newer ticket for that issue here: #775
