### ISSUE TITLE
I don't know anyone who wants to stand for MP

### ISSUE THREAD

**Issue by mwainwright** [mysociety/yournextmp-popit#249]
The page title for yournextmp (which also shows up in Google search results) is

`<title>YourNextMP - Help find candidates for the 2015 UK general election!</title>`

This makes it sound like a page where you suggest that your friends and relations may wish to stand as MPs.

**Comment by zarino** [comment]
Here’s the reason this is important – the Google preview for YourNextMP is the first contact many people will have with YNMP, and we should be certain that it says what we want it to:

![screen shot 2015-03-10 at 09 30 58](https://cloud.githubusercontent.com/assets/739624/6572204/446e9426-c708-11e4-9362-a58b91727363.png)

**Comment by andylolz** [comment]
I don’t know anyone who’s standing either – but I’ve found lots of candidates! :)

**Comment by mhl** [comment]
How about one of these:

* "YourNextMP - Look up candidates for the 2015 UK general election"
* "YourNextMP - Find your local candidates for the 2015 UK general election"

The second has a certain appeal since it can be read either as "look up" or "help with crowd-sourcing", but maybe there are better ways of phrasing it?

**Comment by zarino** [comment]
"YourNextMP – 2015 UK general election candidates" ?

(Nice and short, so it fits entirely into Google's title preview)

**Comment by andylolz** [comment]
Kk cool – sounds good to me
