### ISSUE TITLE
I broke a candidate

### ISSUE THREAD

**Issue by sjorford** [mysociety/yournextmp-popit#263]
I reverted [Farooq Ahmed](https://yournextmp.com/person/6339) as Rochdale First has now been (re-?)added to the EC register, but now the page is coming up as error 500 - I'm guessing because Rochdale First is no longer in the YNMP list of parties?

**Comment by mhl** [comment]
@sjorford Yes, it's rather complicated, I'm afraid. Unfortunately the earlier version that you reverted to, which appeared to refer to Rochdale First, was referring to a version of that party added in error directly in the PopIt organizations collection by one of our volunteer administrators, which is why the page is now broken. I'll fix this and remove that old version from the versions history so that people can't accidentally revert to broken data.

Rochdale First is now in the Electoral Commission's register, but several things need to happen first:
* The OpenElectoralCommission's scraper needs to be run, since YourNextMP uses that as a data source. @symroe has started the scraper, but Rochdale First hasn't appeared in http://openelectoralcommission.org.uk/parties/ or http://openelectoralcommission.org.uk/parties/index.json yet.
* After that, I need to re-run the scraper to update the list of parties that YourNextMP uses.

So, I'm sorry about this - I know it's not ideal, and there's no obvious way you could have known about this.

**Comment by mhl** [comment]
I've unbroken that page now, but I'll leave this open until we've updated the party list.

**Comment by symroe** [comment]
I've just rerun the scraper and updated OpenElectoralCommission

It looks like this is the party we were looking for:

http://openelectoralcommission.org.uk/parties/PP2512/rochdale-first-party/

@mhl There were various other changes that you can see here:

https://github.com/DemocracyClub/UK-Political-Parties/commit/eda7f0ddec74c99804491e5d9e5108939109e416

**Comment by mhl** [comment]
Thanks, @symroe - I've updated the parties and fixed the candidate's party membership.
