### ISSUE TITLE
Missing Party - unable to add candidate

### ISSUE THREAD

**Issue by peterbance** [mysociety/yournextmp-popit#312]
In South West Hertfordshire, we have a candidate standing that is not currently listed.  I tried adding them, but their party isn't in the drop-down list (Common Sense Party).  It appears to be impossible to add a candidate without completing this field.

Is this a bug, or intentional?  I'm happy to add the party myself if there's a way to do so...

**Comment by andylolz** [comment]
Thanks for flagging this up, Peter. The problem was just YourNextMP uses data from the Electoral Commission, but with a bit of a delay. Th Common Sense Party was only registered 2 days before the close of nominations:
http://search.electoralcommission.org.uk/English/Registrations/PP2730

…so it wasn’t yet listed. In any case, it looks as if @mhl has resolved this now:
https://yournextmp.com/constituency/65596/south-west-hertfordshire
